nrfx_rtc: Update logging format to use %lu instead of %d
This patch updates the format used in NRFX_LOG* statements with a %lu (long-unsigned)
instead of %d (int) on the places where a uint32_t is passed as argument.

Example error during compilation:

nrfx_rtc.c:324:24: error: format '%d' expects argument of type 'int',
but argument 3 has type 'uint32_t {aka long unsigned int}'